#!/usr/bin/env bash
# Full benchmark matrix: context size x n-gram table cache state x task shape.
#
# Context matters here for a non-obvious reason. KV is only ~24 KB/token, so a large
# window is cheap in absolute terms -- but every GiB it takes is a GiB the page cache
# cannot use for the 26.8 GiB n-gram table. Since warming that table is worth a lot
# once speculation is on, context size ends up affecting decode throughput indirectly.
#
# This restarts the server once per context size, so it takes roughly 25 minutes.
#
#   MODEL_DIR=... SRC=... ./bench/matrix.sh
#
# Env: CTXS (default "32768 262144"), API, PORT, PY, OUT
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_REPO="$(cd "$HERE/.." && pwd)"
CTXS="${CTXS:-32768 262144}"
PORT="${PORT:-8000}"
API="${API:-http://127.0.0.1:$PORT}"
PY="${PY:-python3}"
OUT="${OUT:-$HERE/matrix-results.md}"

: "${MODEL_DIR:?set MODEL_DIR}"
: "${SRC:?set SRC (llama.cpp checkout)}"
QUANT="${QUANT:-UD-Q4_K_XL}"
MODEL="$(ls "$MODEL_DIR/$QUANT"/*00001-of-*.gguf | head -1)"

drop_caches() {
  if [ "$(id -u)" = "0" ]; then sync; echo 3 > /proc/sys/vm/drop_caches; return 0; fi
  command -v docker >/dev/null 2>&1 &&
    docker run --rm --privileged alpine sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches' 2>/dev/null && return 0
  sudo -n sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches' 2>/dev/null && return 0
  return 1
}

wait_ready() {
  for _ in $(seq 1 60); do
    [ "$(curl -s -m 3 "$API/health" 2>/dev/null)" = '{"status":"ok"}' ] && return 0
    sleep 20
  done
  return 1
}

: > "$OUT"
echo "# Benchmark matrix" >> "$OUT"
echo >> "$OUT"
echo "Context size x n-gram table cache state. Generated by \`bench/matrix.sh\`." >> "$OUT"
echo >> "$OUT"

for CTX in $CTXS; do
  echo "=== ctx $CTX: starting server ===" >&2
  pkill -x llama-server 2>/dev/null; sleep 6
  ( cd "$ROOT_REPO" && MODEL_DIR="$MODEL_DIR" SRC="$SRC" CTX="$CTX" PORT="$PORT" \
      HOST=127.0.0.1 WARM=0 ./run.sh serve > /tmp/matrix-serve-$CTX.log 2>&1 & )
  if ! wait_ready; then
    echo "ctx $CTX: server did not come up, skipping" >&2
    echo "## ctx $CTX: server failed to start" >> "$OUT"; continue
  fi

  echo "=== ctx $CTX: cold pass ===" >&2
  drop_caches || echo "   (could not drop caches; measuring current state)" >&2
  COLD_PCT="$("$PY" "$ROOT_REPO/tools/page_cache.py" "$MODEL" 2>/dev/null | grep -o '[0-9.]*%' | tail -1)"
  "$PY" "$HERE/run_bench.py" --api "$API" --model "$MODEL" \
       --label "ctx $CTX, table cold (${COLD_PCT:-?})" --skip-ctx >> "$OUT"

  echo "=== ctx $CTX: warming ===" >&2
  "$PY" "$ROOT_REPO/tools/warm_table.py" "$MODEL" >&2
  WARM_PCT="$("$PY" "$ROOT_REPO/tools/page_cache.py" "$MODEL" 2>/dev/null | grep -o '[0-9.]*%' | tail -1)"
  "$PY" "$HERE/run_bench.py" --api "$API" --model "$MODEL" \
       --label "ctx $CTX, table warm (${WARM_PCT:-?})" --skip-ctx >> "$OUT"

  echo "=== ctx $CTX: context ladder ===" >&2
  "$PY" "$HERE/run_bench.py" --api "$API" --model "$MODEL" \
       --label "ctx $CTX, prefill/decode ladder" --skip-tasks >> "$OUT"
done

echo >> "$OUT"
echo "Every run is one request at a time. Concurrent requests do not abort the server -" >> "$OUT"
echo "they queue at --parallel 1, and batch at higher settings - but this matrix does not" >> "$OUT"
echo "measure them, so treat every figure here as single-stream." >> "$OUT"
echo "Results written to $OUT" >&2
